#ifndef RK_VERSION_H
#define RK_VERSION_H

#define RK_VERSION_STRINGIFY(n) #n
#define RK_VERSION_TOSTR(n) RK_VERSION_STRINGIFY(n)

#define RK_VERSION_COUNT 1
#define RK_VERSION_STR "rel-" RK_VERSION_TOSTR(RK_VERSION_COUNT)

#endif
